openapi: 3.0.3
info:
  title: Pipeline service
  description: 
    This is a pipeline service that can create pipelines, start them and get status of runned job.

  version: 1.0.0
tags:
  - name: pipelines
    description: Everything about pipelines
  - name: jobs
    description: Everything about jobs
paths:
  /pipeline:
    post:
      tags:
        - pipelines
      summary: Create new pipeline
      description: Create new pipeline
      operationId: create_pipeline
      requestBody:
        description: Create new pipeline
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pipeline'
        required: true
      responses:
        '200':
          description: Successful creation
        '400':
          description: Invalid input
        '409':
          description: Name of pipeline has already used
        '422':
          description: Validation exception
  /job/{pipeline_name}:
    post:
      tags:
        - jobs
      summary: Start job with existing pipeline
      description: Start job with existing pipeline
      operationId: start_pipeline_by_name
      parameters:
          - name: pipeline_name
            in: path
            description: Name of pipeline that needs to be started
            required: true
            schema:
              type: string
      requestBody:
        description: Start job with existing pipeline
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StartJobSchema'
        required: true
      responses:
        '200':
          description: Successful start pipeline
          content:
            application/json:
              schema:
                type: integer
                description: ID started job
                example: 10     
        '400':
          description: Invalid input
        '422':
          description: Validation exception
  /job:
    get:
      tags:
        - jobs
      summary: Status of runned job
      description: Status of runned job
      operationId: status_job_by_id
      parameters:
        - name: job_id
          in: query
          description: Id of runned job
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Status of job
          content:
            application/json:
              schema:
                type: object
                oneOf:
                  - $ref: '#/components/schemas/SuccessEndedJob'
                  - $ref: '#/components/schemas/JobEndedWithError'
                  - $ref: '#/components/schemas/JobInProcess'
                  
        '400':
          description: Invalid input
  
  
components:
  schemas:
    Pipeline:
      type: object
      required:
        - pipeline_name
        - stages
      properties:
        pipeline_name:
          type: string
          maxLength: 50
          description: Name of pipeline
          example: Authorization
        stages:
          type: object
          description: Description of every stage in pipeline with its order number as key
          additionalProperties: 
            $ref: '#/components/schemas/Stage'
          example: 
            1:
              stage_type: HTTP
              stage_params:
                url_path: server.com/users
                method: POST
                input_data: 
                  "login": ".login"
                  "password": ".password"
                return_value: 
                  "user_id": ".user_id"
                return_codes: [200]
            2:
              stage_type: HTTP
              stage_params:
                url_path: server.com/auth
                method: POST
                input_data: 
                  "user_id": ".user_id"
                return_value: 
                  "jwt": ".jwt"
                return_codes: [200]  
            
    Stage:
      type: object
      required:
        - stage_type
        - stage_params
      properties:
        stage_type:
          type: string
          maxLength: 50
          description: Type of stage
          enum:
            - HTTP
            - Database
          example: HTTP
        stage_params:
          type: object
          description: Parameters of stage
          oneOf:
            - $ref: '#/components/schemas/HTTPStage'
            - $ref: '#/components/schemas/DatabaseStage'
    HTTPStage:
      type: object
      required:
        - url_path
        - method
        - return_codes
      properties:
        url_path:
          type: string
          maxLength: 50
          description: URL-path to service
          example: server.com/users
        method:
          type: string
          description: HTTP-method of request
          enum:
            - POST
            - GET
          example: POST
        input_data:
          type: object
          description: HashMap of keys of input data that consist of path and query parameters and data needed in request with jq filters needed to convert them from incoming data 
          additionalProperties:
            type: string
            maxLength: 50
          example:
            "path_key1": ".path_filter1"
            "path_key2": ".path_filter2"
            "query_key1": ".query_filter1"
            "query_key2": ".query_filter2"
            "data_key1": ".data_filter1"
            "data_key2": ".data_filter2"
        return_values:
          type: object
          description: HashMap of keys of return values of stage with jq filters needed to transform them to data sended to next stage
          additionalProperties:
            type: string
            maxLength: 50
          example:
            "return_value_key1": ".return_filter1"
            "return_value_key2": ".return_filter2"
        return_codes:
          type: array
          description: Correct HTTP-responce codes to continue execute stages
          items:
            type: integer
          example: [200, 201]
    
    DatabaseStage:
      type: object
      properties:
        request:
          type: string
          maxLength: 50
          description: Request to databse
          example: select * from db
    StartJobSchema:
      type: object
      additionalProperties:
        type: string
        maxLength: 50
      description:  Key/value for input data
      example: 
        path_key1: "path_value1"
        path_key2: "path_value2"
        query_key1: "query_value1"
        query_key2: "query_value2"
        data_key1: "data_value1"
        data_key2: "data_value2"
    SuccessEndedJob:
      type: string
      example: Success ended
    JobInProcess:
      type: string
      description: Message about processing job with id of current executing stage
      example: Job in process on stage 2
    JobEndedWithError:
      type: object
      properties:
        error_code:
          type: integer
          description: Error code
          example: 409
        error_message:
          type: string
          description: Error message
          example: Can't insert into database via conflict name
